### ISSUE TITLE
ReferenceError: 'TextEncoder' is not defined in Ms Edge

### ISSUE THREAD

**Issue by RaschidJFR** [kchapelier/in-browser-download#1]
Got this error on calling the function

```
ReferenceError: 'TextEncoder' is not defined
```

**Comment by RaschidJFR** [comment]
Got a workaround installing the `text-encoding` pollyfill:

https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/2018/06/29/pollyfils-for-stompjs-v5.html

**Comment by kchapelier** [comment]
Yes, this requirement is explained in the README. The 1.x.x version of this module uses less modern / more widely supported API but is also potentially slower and incurs a slightly larger bundle size.
